name: load-dataset-actions
on: [workflow_dispatch]
jobs:
  load_dataset:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download file from Github
        run: curl -o dataset.tsv https://raw.githubusercontent.com/WebOfRussia/financial-news-sentiment/main/data/data.tsv
      - name: Load dataset
        run: python3 src/load_dataset.py dataset.tsv