name: load-dataset-actions
on: [workflow_dispatch]
jobs:
  load_dataset:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download file from Github
        run: curl -o dataset.tsv https://raw.githubusercontent.com/WebOfRussia/financial-news-sentiment/main/data/data.tsv
      - name: Load dataset
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/load_dataset.py dataset.tsv
  handle_dataset:
    runs-on: self-hosted
    needs: load_dataset
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Handle dataset
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD:  ${{secrets.DB_PASSWORD}}
        run: python3 src/handle_dataset.py