name: main-actions
on: [workflow_dispatch]
jobs:
  fit_models:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fit models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 0
        run: python3 src/fit_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'Commit changes of version'
        run: git push
  estimate_models:
    runs-on: self-hosted
    needs: fit_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 0
        run: python3 src/estimate_models.py
  choose_best_model:
    runs-on: self-hosted
    needs: estimate_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Choose the best model
        env:
          INC: 0
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/choose_model.py
  extra_fit_models:
    permissions:
      contents: write
    runs-on: self-hosted
    needs: choose_best_model
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 1
        run: python3 src/extra_fit_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'Commit changes of version'
  second_estimate_models:
    runs-on: self-hosted
    needs: extra_fit_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 1
        run: python3 src/estimate_models.py
  extra_choose_best_model:
    runs-on: self-hosted
    needs: second_estimate_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Choose the best model
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 1
        run: python3 src/choose_model.py
