name: main-actions
on: [workflow_dispatch]
jobs:
  Fit_models:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fit models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 fit_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'Commit changes of version'
  Estimate_models:
    runs-on: self-hosted
    needs: Fit_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 estimate_models.py
