name: main-actions
on:
  workflow_dispatch:
    inputs:
      is_train:
        description: Mode of pipeline
        required: true
        default: 'true'
jobs:
  fit_models:
    if: github.event.inputs.is_train == 'true'
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fit models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 0
        run: python3 src/fit_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'Commit changes of version'
  extra_fit_models:
    if: github.event.inputs.is_train == 'false'
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 0
        run: python3 src/extra_fit_models.py
  estimate_models:
    runs-on: self-hosted
    needs: [fit_models, extra_fit_models]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Estimate models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          INC: 0
        run: python3 src/estimate_models.py
  choose_best_model:
    runs-on: self-hosted
    needs: estimate_models
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Choose the best model
        env:
          INC: 0
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/choose_model.py
  deploy:
    runs-on: self-hosted
    needs: choose_best_model
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start deploy
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 app.py
